/**
 * Hand-written aliases over the generated schema. `types.ts` is generated by
 * `npm run gen:api` and must not be hand-edited — everything here just pins a
 * friendly name onto the generated DTO shapes.
 */
import type { components } from './types';

export type PublicOrganization = components['schemas']['PublicOrganizationDto'];
export type PublicService = components['schemas']['PublicServiceDto'];
export type PublicResource = components['schemas']['PublicResourceDto'];
export type PublicSlot = components['schemas']['PublicSlotDto'];
export type PublicBookingResponse = components['schemas']['PublicBookingResponseDto'];
