// GENERATED — do not hand-edit.
// Regenerate with `npm run gen:api` (the backend must be running on :3005).
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and receive an httpOnly session cookie */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke every session belonging to this user */
        post: operations["AuthController_logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active sessions for the signed-in user */
        get: operations["AuthController_listSessions"];
        put?: never;
        post?: never;
        /** Revoke one session belonging to this user */
        delete: operations["AuthController_revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change your own password */
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users in your organization */
        get: operations["UserController_findAll"];
        put?: never;
        /** Create a user in your organization */
        post: operations["UserController_create"];
        /** Delete a user */
        delete: operations["UserController_remove"];
        options?: never;
        head?: never;
        /** Update a user */
        patch: operations["UserController_update"];
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations */
        get: operations["OrganizationController_findAll"];
        put?: never;
        /** Create organization */
        post: operations["OrganizationController_create"];
        /** Delete organization */
        delete: operations["OrganizationController_remove"];
        options?: never;
        head?: never;
        /** Update organization */
        patch: operations["OrganizationController_update"];
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers */
        get: operations["CustomerController_findAll"];
        put?: never;
        /** Create customer */
        post: operations["CustomerController_create"];
        delete: operations["CustomerController_remove"];
        options?: never;
        head?: never;
        patch: operations["CustomerController_update"];
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List resources */
        get: operations["ResourceController_findAll"];
        put?: never;
        /** Create resource */
        post: operations["ResourceController_create"];
        delete: operations["ResourceController_remove"];
        options?: never;
        head?: never;
        patch: operations["ResourceController_update"];
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List services */
        get: operations["ServiceController_findAll"];
        put?: never;
        /** Create service */
        post: operations["ServiceController_create"];
        delete: operations["ServiceController_remove"];
        options?: never;
        head?: never;
        patch: operations["ServiceController_update"];
        trace?: never;
    };
    "/availability-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List availability-rules */
        get: operations["AvailabilityRuleController_findAll"];
        put?: never;
        /** Create availability-rule */
        post: operations["AvailabilityRuleController_create"];
        delete: operations["AvailabilityRuleController_remove"];
        options?: never;
        head?: never;
        patch: operations["AvailabilityRuleController_update"];
        trace?: never;
    };
    "/availability-exceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List availability-exceptions */
        get: operations["AvailabilityExceptionController_findAll"];
        put?: never;
        /** Create availability-exception */
        post: operations["AvailabilityExceptionController_create"];
        delete: operations["AvailabilityExceptionController_remove"];
        options?: never;
        head?: never;
        patch: operations["AvailabilityExceptionController_update"];
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookings */
        get: operations["BookingController_findAll"];
        put?: never;
        /** Create booking */
        post: operations["BookingController_create"];
        delete: operations["BookingController_remove"];
        options?: never;
        head?: never;
        patch: operations["BookingController_update"];
        trace?: never;
    };
    "/booking-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List booking-events */
        get: operations["BookingEventController_findAll"];
        put?: never;
        /** Create booking-event */
        post: operations["BookingEventController_create"];
        delete: operations["BookingEventController_remove"];
        options?: never;
        head?: never;
        patch: operations["BookingEventController_update"];
        trace?: never;
    };
    "/booking-participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List booking-participants */
        get: operations["BookingParticipantController_findAll"];
        put?: never;
        /** Create booking-participant */
        post: operations["BookingParticipantController_create"];
        delete: operations["BookingParticipantController_remove"];
        options?: never;
        head?: never;
        patch: operations["BookingParticipantController_update"];
        trace?: never;
    };
    "/booking-resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List booking-resources */
        get: operations["BookingResourceController_findAll"];
        put?: never;
        post: operations["BookingResourceController_create"];
        delete: operations["BookingResourceController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List service-resources */
        get: operations["ServiceResourceController_findAll"];
        put?: never;
        post: operations["ServiceResourceController_create"];
        delete: operations["ServiceResourceController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/orgs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up an organization by its public slug */
        get: operations["PublicBookingController_getOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/orgs/{slug}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookable services for an organization */
        get: operations["PublicBookingController_listServices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/orgs/{slug}/services/{serviceId}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List resources a guest may choose for a CUSTOMER_CHOICE service */
        get: operations["PublicBookingController_listResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/orgs/{slug}/services/{serviceId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find bookable slots for a service */
        get: operations["PublicBookingController_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/orgs/{slug}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book a slot as a guest */
        post: operations["PublicBookingController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @example berkay@example.com */
            email: string;
            /** @example berkay123 */
            password: string;
            /** Format: uuid */
            organizationId?: string;
        };
        AuthUserDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** @example berkay@example.com */
            email: string;
            /** @example Berkay Bayar */
            name: string;
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "STAFF" | "CUSTOMER";
        };
        SessionDto: {
            /** Format: uuid */
            id: string;
            current: boolean;
            userAgent: Record<string, never> | null;
            ip: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ChangePasswordDto: {
            /** @example berkay123 */
            currentPassword: string;
            /** @example berkay1234 */
            newPassword: string;
            /** @default true */
            revokeOtherSessions: boolean;
        };
        UserResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** @example Berkay Bayar */
            name: string;
            /** @example berkay@example.com */
            email: string;
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "STAFF" | "CUSTOMER";
            hasPassword: boolean;
            metadata: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateUserDto: {
            /** @example Berkay Bayar */
            name: string;
            /** @example berkay@example.com */
            email: string;
            /** @example berkay123 */
            password?: string;
            /**
             * @default STAFF
             * @enum {string}
             */
            role: "OWNER" | "ADMIN" | "STAFF" | "CUSTOMER";
            /** @example {} */
            metadata?: Record<string, never>;
        };
        UpdateUserDto: {
            /** Format: uuid */
            id: string;
            /** @example Berkay Bayar */
            name?: string;
            /** @example berkay@example.com */
            email?: string;
            /** @example berkay123 */
            password?: string;
            /** @enum {string} */
            role?: "OWNER" | "ADMIN" | "STAFF" | "CUSTOMER";
            /** @example {} */
            metadata?: Record<string, never>;
        };
        OrganizationResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            timezone: string;
            metadata: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateOrganizationDto: {
            /** @example Septem Montes */
            name: string;
            /** @example septem-montes */
            slug: string;
            /**
             * @default utc
             * @example Europe/Bucharest
             */
            timezone: string;
            /** @example {} */
            metadata?: Record<string, never>;
        };
        UpdateOrganizationDto: {
            /** Format: uuid */
            id: string;
            name?: string;
            slug?: string;
            timezone?: string;
            metadata?: Record<string, never>;
        };
        CustomerResponseDto: {
            /** Format: uuid */
            id: string;
        };
        CreateCustomerDto: {
            /** Format: uuid */
            organizationId: string;
            name: string;
            email?: string;
            phone?: string;
            /** @example {} */
            metadata?: Record<string, never>;
        };
        UpdateCustomerDto: {
            /** Format: uuid */
            id: string;
            name?: string;
            email?: string;
            phone?: string;
            metadata?: Record<string, never>;
        };
        ResourceResponseDto: {
            /** Format: uuid */
            id: string;
        };
        CreateResourceDto: {
            /** Format: uuid */
            organizationId: string;
            name: string;
            resourceType?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            /** Format: uuid */
            organizationsId: string;
            /** @example {} */
            metadata?: Record<string, never>;
        };
        UpdateResourceDto: {
            /** Format: uuid */
            id: string;
            name?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            metadata?: Record<string, never>;
        };
        ServiceResponseDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            resourceSelectionMode: "AUTO" | "CUSTOMER_CHOICE";
        };
        CreateServiceDto: {
            /** Format: uuid */
            organizationId: string;
            name: string;
            description?: string;
            durationMinutes: number;
            /** @default 0 */
            bufferBeforeMinutes: number;
            /** @default 0 */
            bufferAfterMinutes: number;
            /** @default true */
            isActive: boolean;
            /** @enum {string} */
            resourceSelectionMode?: "AUTO" | "CUSTOMER_CHOICE";
            /** @example {} */
            metadata?: Record<string, never>;
        };
        UpdateServiceDto: {
            /** Format: uuid */
            id: string;
            name?: string;
            durationMinutes?: number;
            isActive?: boolean;
            /** @enum {string} */
            resourceSelectionMode?: "AUTO" | "CUSTOMER_CHOICE";
            metadata?: Record<string, never>;
        };
        AvailabilityRuleResponseDto: {
            /** Format: uuid */
            id: string;
        };
        CreateAvailabilityRuleDto: {
            resourceId: string;
            dayOfWeek: number;
            /** @example 09:00:00 */
            startTime: string;
            /** @example 17:00:00 */
            endTime: string;
            timezone?: string;
            /** @default true */
            isActive: boolean;
            /** @example {} */
            metadata?: Record<string, never>;
        };
        UpdateAvailabilityRuleDto: {
            /** Format: uuid */
            id: string;
            dayOfWeek?: number;
            startTime?: string;
            endTime?: string;
            isActive?: boolean;
            metadata?: Record<string, never>;
        };
        AvailabilityExceptionResponseDto: {
            /** Format: uuid */
            id: string;
        };
        CreateAvailabilityExceptionDto: {
            resourceId: string;
            /** @example 2026-08-20 */
            exceptionDate: string;
            /** @example 09:00:00 */
            startTime: string;
            /** @example 12:00:00 */
            endTime: string;
            /** @enum {string} */
            exceptionType: "UNAVAILABLE" | "AVAILABLE";
            reason?: string;
            /** @example {} */
            metadata?: Record<string, never>;
        };
        UpdateAvailabilityExceptionDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            exceptionType?: "UNAVAILABLE" | "AVAILABLE";
            reason?: string;
            metadata?: Record<string, never>;
        };
        BookingResponseDto: {
            /** Format: uuid */
            id: string;
        };
        CreateBookingDto: {
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            customerId?: string;
            /** Format: uuid */
            serviceId?: string;
            startsAt: string;
            endsAt: string;
            /** @enum {string} */
            status?: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED" | "NO_SHOW";
            title?: string;
            notes?: string;
            /** @example {} */
            metadata?: Record<string, never>;
        };
        UpdateBookingDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status?: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED" | "NO_SHOW";
            title?: string;
            notes?: string;
            metadata?: Record<string, never>;
        };
        BookingEventResponseDto: {
            /** Format: uuid */
            id: string;
        };
        CreateBookingEventDto: {
            bookingId: string;
            /** Format: uuid */
            actorUserId?: string;
            /** @enum {string} */
            eventType: "CREATED" | "CONFIRMED" | "CANCELLED" | "RESCHEDULED" | "COMPLETED" | "NO_SHOW";
            /** @example {} */
            metadata?: Record<string, never>;
        };
        UpdateBookingEventDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            eventType?: "CREATED" | "CONFIRMED" | "CANCELLED" | "RESCHEDULED" | "COMPLETED" | "NO_SHOW";
            metadata?: Record<string, never>;
        };
        BookingParticipantResponseDto: {
            /** Format: uuid */
            id: string;
        };
        CreateBookingParticipantDto: {
            bookingId: string;
            /** Format: uuid */
            customerId?: string;
            /** Format: uuid */
            userId?: string;
            role?: string;
            /** @example {} */
            metadata?: Record<string, never>;
        };
        UpdateBookingParticipantDto: {
            /** Format: uuid */
            id: string;
            role?: string;
            metadata?: Record<string, never>;
        };
        CreateBookingResourceDto: {
            /** Format: uuid */
            bookingId: string;
            /** Format: uuid */
            resourceId: string;
        };
        CreateServiceResourceDto: {
            /** Format: uuid */
            serviceId: string;
            /** Format: uuid */
            resourceId: string;
        };
        PublicOrganizationDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** @example Europe/Istanbul */
            timezone: string;
        };
        PublicServiceDto: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            durationMinutes: number;
            /** @enum {string} */
            resourceSelectionMode: "AUTO" | "CUSTOMER_CHOICE";
        };
        PublicResourceDto: {
            /** Format: uuid */
            id: string;
            name: string;
            resourceType: string | null;
        };
        PublicSlotDto: {
            /** @description ISO-8601 UTC start of the slot */
            startsAt: string;
            /** @description ISO-8601 UTC end of the slot */
            endsAt: string;
            resourceIds: string[];
        };
        PublicCustomerDto: {
            name: string;
            email: string;
            phone?: string;
        };
        CreatePublicBookingDto: {
            /** Format: uuid */
            serviceId: string;
            /** @description ISO-8601 instant with explicit UTC offset; must match a slot start exactly */
            startsAt: string;
            /** Format: uuid */
            resourceId?: string;
            customer: components["schemas"]["PublicCustomerDto"];
            notes?: string;
        };
        PublicBookingResponseDto: {
            /** Format: uuid */
            bookingId: string;
            startsAt: string;
            endsAt: string;
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED" | "NO_SHOW";
            serviceName: string;
            resourceName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    AuthController_listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"][];
                };
            };
        };
    };
    AuthController_revokeSession: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_findAll: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    UserController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UserController_remove: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    OrganizationController_findAll: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponseDto"][];
                };
            };
        };
    };
    OrganizationController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponseDto"];
                };
            };
        };
    };
    OrganizationController_remove: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrganizationController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponseDto"];
                };
            };
        };
    };
    CustomerController_findAll: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponseDto"][];
                };
            };
        };
    };
    CustomerController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomerController_remove: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomerController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResourceController_findAll: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceResponseDto"][];
                };
            };
        };
    };
    ResourceController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResourceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResourceController_remove: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResourceController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResourceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServiceController_findAll: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceResponseDto"][];
                };
            };
        };
    };
    ServiceController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServiceController_remove: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServiceController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServiceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AvailabilityRuleController_findAll: {
        parameters: {
            query?: {
                id?: string;
                resourceId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityRuleResponseDto"][];
                };
            };
        };
    };
    AvailabilityRuleController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAvailabilityRuleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AvailabilityRuleController_remove: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AvailabilityRuleController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAvailabilityRuleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AvailabilityExceptionController_findAll: {
        parameters: {
            query?: {
                id?: string;
                resourceId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityExceptionResponseDto"][];
                };
            };
        };
    };
    AvailabilityExceptionController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAvailabilityExceptionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AvailabilityExceptionController_remove: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AvailabilityExceptionController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAvailabilityExceptionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingController_findAll: {
        parameters: {
            query?: {
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingResponseDto"][];
                };
            };
        };
    };
    BookingController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingController_remove: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBookingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingEventController_findAll: {
        parameters: {
            query?: {
                id?: string;
                bookingId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEventResponseDto"][];
                };
            };
        };
    };
    BookingEventController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingEventController_remove: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingEventController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBookingEventDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingParticipantController_findAll: {
        parameters: {
            query?: {
                id?: string;
                bookingId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingParticipantResponseDto"][];
                };
            };
        };
    };
    BookingParticipantController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingParticipantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingParticipantController_remove: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingParticipantController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBookingParticipantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingResourceController_findAll: {
        parameters: {
            query?: {
                bookingId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingResourceController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingResourceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BookingResourceController_remove: {
        parameters: {
            query: {
                bookingId: string;
                resourceId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServiceResourceController_findAll: {
        parameters: {
            query?: {
                serviceId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServiceResourceController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServiceResourceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ServiceResourceController_remove: {
        parameters: {
            query: {
                serviceId: string;
                resourceId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicBookingController_getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicOrganizationDto"];
                };
            };
            /** @description Unknown organization slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicBookingController_listServices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicServiceDto"][];
                };
            };
            /** @description Unknown organization slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicBookingController_listResources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                serviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicResourceDto"][];
                };
            };
            /** @description Unknown service, or the service does not offer a choice */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicBookingController_listSlots: {
        parameters: {
            query: {
                /** @description Local date in the org timezone */
                from: string;
                to: string;
                resourceId?: string;
            };
            header?: never;
            path: {
                slug: string;
                serviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSlotDto"][];
                };
            };
            /** @description Date range must cover 1 to 31 days */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown organization slug or service */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicBookingController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePublicBookingDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicBookingResponseDto"];
                };
            };
            /** @description Validation failure, or an unparseable startsAt */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown organization slug, unknown/inactive/unbookable service, or bad resourceId */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Slot already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
